// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/auction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Auction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SellerId      string                 `protobuf:"bytes,2,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	StartPrice    float64                `protobuf:"fixed64,5,opt,name=start_price,json=startPrice,proto3" json:"start_price,omitempty"`
	CurrentPrice  float64                `protobuf:"fixed64,6,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // ACTIVE, CLOSED, PENDING, CANCELLED
	StartTime     int64                  `protobuf:"varint,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,9,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Category      string                 `protobuf:"bytes,10,opt,name=category,proto3" json:"category,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,11,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auction) Reset() {
	*x = Auction{}
	mi := &file_proto_auction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auction) ProtoMessage() {}

func (x *Auction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auction.ProtoReflect.Descriptor instead.
func (*Auction) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{0}
}

func (x *Auction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Auction) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *Auction) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Auction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Auction) GetStartPrice() float64 {
	if x != nil {
		return x.StartPrice
	}
	return 0
}

func (x *Auction) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *Auction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Auction) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Auction) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Auction) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Auction) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type CreateAuctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SellerId      string                 `protobuf:"bytes,1,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartPrice    float64                `protobuf:"fixed64,4,opt,name=start_price,json=startPrice,proto3" json:"start_price,omitempty"`
	StartTime     int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Category      string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,8,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuctionRequest) Reset() {
	*x = CreateAuctionRequest{}
	mi := &file_proto_auction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuctionRequest) ProtoMessage() {}

func (x *CreateAuctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuctionRequest.ProtoReflect.Descriptor instead.
func (*CreateAuctionRequest) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAuctionRequest) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *CreateAuctionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAuctionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAuctionRequest) GetStartPrice() float64 {
	if x != nil {
		return x.StartPrice
	}
	return 0
}

func (x *CreateAuctionRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CreateAuctionRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *CreateAuctionRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateAuctionRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type CreateAuctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auction       *Auction               `protobuf:"bytes,1,opt,name=auction,proto3" json:"auction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuctionResponse) Reset() {
	*x = CreateAuctionResponse{}
	mi := &file_proto_auction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuctionResponse) ProtoMessage() {}

func (x *CreateAuctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuctionResponse.ProtoReflect.Descriptor instead.
func (*CreateAuctionResponse) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAuctionResponse) GetAuction() *Auction {
	if x != nil {
		return x.Auction
	}
	return nil
}

type GetAuctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuctionRequest) Reset() {
	*x = GetAuctionRequest{}
	mi := &file_proto_auction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuctionRequest) ProtoMessage() {}

func (x *GetAuctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuctionRequest.ProtoReflect.Descriptor instead.
func (*GetAuctionRequest) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{3}
}

func (x *GetAuctionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAuctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auction       *Auction               `protobuf:"bytes,1,opt,name=auction,proto3" json:"auction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuctionResponse) Reset() {
	*x = GetAuctionResponse{}
	mi := &file_proto_auction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuctionResponse) ProtoMessage() {}

func (x *GetAuctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuctionResponse.ProtoReflect.Descriptor instead.
func (*GetAuctionResponse) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{4}
}

func (x *GetAuctionResponse) GetAuction() *Auction {
	if x != nil {
		return x.Auction
	}
	return nil
}

type ListAuctionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                     // Optional filter
	SellerId      string                 `protobuf:"bytes,4,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"` // Optional filter
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`                 // Optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuctionsRequest) Reset() {
	*x = ListAuctionsRequest{}
	mi := &file_proto_auction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuctionsRequest) ProtoMessage() {}

func (x *ListAuctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuctionsRequest.ProtoReflect.Descriptor instead.
func (*ListAuctionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{5}
}

func (x *ListAuctionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAuctionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAuctionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListAuctionsRequest) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *ListAuctionsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ListAuctionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auctions      []*Auction             `protobuf:"bytes,1,rep,name=auctions,proto3" json:"auctions,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuctionsResponse) Reset() {
	*x = ListAuctionsResponse{}
	mi := &file_proto_auction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuctionsResponse) ProtoMessage() {}

func (x *ListAuctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuctionsResponse.ProtoReflect.Descriptor instead.
func (*ListAuctionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{6}
}

func (x *ListAuctionsResponse) GetAuctions() []*Auction {
	if x != nil {
		return x.Auctions
	}
	return nil
}

func (x *ListAuctionsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UpdateAuctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAuctionRequest) Reset() {
	*x = UpdateAuctionRequest{}
	mi := &file_proto_auction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAuctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAuctionRequest) ProtoMessage() {}

func (x *UpdateAuctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAuctionRequest.ProtoReflect.Descriptor instead.
func (*UpdateAuctionRequest) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAuctionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAuctionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateAuctionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateAuctionRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type UpdateAuctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auction       *Auction               `protobuf:"bytes,1,opt,name=auction,proto3" json:"auction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAuctionResponse) Reset() {
	*x = UpdateAuctionResponse{}
	mi := &file_proto_auction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAuctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAuctionResponse) ProtoMessage() {}

func (x *UpdateAuctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAuctionResponse.ProtoReflect.Descriptor instead.
func (*UpdateAuctionResponse) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAuctionResponse) GetAuction() *Auction {
	if x != nil {
		return x.Auction
	}
	return nil
}

type CloseAuctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseAuctionRequest) Reset() {
	*x = CloseAuctionRequest{}
	mi := &file_proto_auction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseAuctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseAuctionRequest) ProtoMessage() {}

func (x *CloseAuctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseAuctionRequest.ProtoReflect.Descriptor instead.
func (*CloseAuctionRequest) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{9}
}

func (x *CloseAuctionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CloseAuctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseAuctionResponse) Reset() {
	*x = CloseAuctionResponse{}
	mi := &file_proto_auction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseAuctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseAuctionResponse) ProtoMessage() {}

func (x *CloseAuctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseAuctionResponse.ProtoReflect.Descriptor instead.
func (*CloseAuctionResponse) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{10}
}

func (x *CloseAuctionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CloseAuctionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Existing messages
type BidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     string                 `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	BidderId      string                 `protobuf:"bytes,3,opt,name=bidder_id,json=bidderId,proto3" json:"bidder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_proto_auction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{11}
}

func (x *BidRequest) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

func (x *BidRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BidRequest) GetBidderId() string {
	if x != nil {
		return x.BidderId
	}
	return ""
}

type BidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	CurrentPrice  float64                `protobuf:"fixed64,2,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	mi := &file_proto_auction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{12}
}

func (x *BidResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *BidResponse) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *BidResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     string                 `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_auction_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{13}
}

func (x *StatusRequest) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     string                 `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CurrentPrice  float64                `protobuf:"fixed64,3,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	EndTimeUnix   int64                  `protobuf:"varint,5,opt,name=end_time_unix,json=endTimeUnix,proto3" json:"end_time_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_auction_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{14}
}

func (x *StatusResponse) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

func (x *StatusResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StatusResponse) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetEndTimeUnix() int64 {
	if x != nil {
		return x.EndTimeUnix
	}
	return 0
}

var File_proto_auction_proto protoreflect.FileDescriptor

const file_proto_auction_proto_rawDesc = "" +
	"\n" +
	"\x13proto/auction.proto\x12\rproto.auction\"\xbf\x02\n" +
	"\aAuction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tseller_id\x18\x02 \x01(\tR\bsellerId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\vstart_price\x18\x05 \x01(\x01R\n" +
	"startPrice\x12#\n" +
	"\rcurrent_price\x18\x06 \x01(\x01R\fcurrentPrice\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\b \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\t \x01(\x03R\aendTime\x12\x1a\n" +
	"\bcategory\x18\n" +
	" \x01(\tR\bcategory\x12\x1b\n" +
	"\timage_url\x18\v \x01(\tR\bimageUrl\"\xff\x01\n" +
	"\x14CreateAuctionRequest\x12\x1b\n" +
	"\tseller_id\x18\x01 \x01(\tR\bsellerId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vstart_price\x18\x04 \x01(\x01R\n" +
	"startPrice\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x1b\n" +
	"\timage_url\x18\b \x01(\tR\bimageUrl\"I\n" +
	"\x15CreateAuctionResponse\x120\n" +
	"\aauction\x18\x01 \x01(\v2\x16.proto.auction.AuctionR\aauction\"#\n" +
	"\x11GetAuctionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x12GetAuctionResponse\x120\n" +
	"\aauction\x18\x01 \x01(\v2\x16.proto.auction.AuctionR\aauction\"\x90\x01\n" +
	"\x13ListAuctionsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\tseller_id\x18\x04 \x01(\tR\bsellerId\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\"k\n" +
	"\x14ListAuctionsResponse\x122\n" +
	"\bauctions\x18\x01 \x03(\v2\x16.proto.auction.AuctionR\bauctions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"{\n" +
	"\x14UpdateAuctionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\"I\n" +
	"\x15UpdateAuctionResponse\x120\n" +
	"\aauction\x18\x01 \x01(\v2\x16.proto.auction.AuctionR\aauction\"%\n" +
	"\x13CloseAuctionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x14CloseAuctionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"`\n" +
	"\n" +
	"BidRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\tR\tauctionId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1b\n" +
	"\tbidder_id\x18\x03 \x01(\tR\bbidderId\"g\n" +
	"\vBidResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12#\n" +
	"\rcurrent_price\x18\x02 \x01(\x01R\fcurrentPrice\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\".\n" +
	"\rStatusRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\tR\tauctionId\"\xa6\x01\n" +
	"\x0eStatusResponse\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\tR\tauctionId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12#\n" +
	"\rcurrent_price\x18\x03 \x01(\x01R\fcurrentPrice\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\"\n" +
	"\rend_time_unix\x18\x05 \x01(\x03R\vendTimeUnix2\xe4\x04\n" +
	"\x0eAuctionService\x12D\n" +
	"\vValidateBid\x12\x19.proto.auction.BidRequest\x1a\x1a.proto.auction.BidResponse\x12O\n" +
	"\x10GetAuctionStatus\x12\x1c.proto.auction.StatusRequest\x1a\x1d.proto.auction.StatusResponse\x12Z\n" +
	"\rCreateAuction\x12#.proto.auction.CreateAuctionRequest\x1a$.proto.auction.CreateAuctionResponse\x12Q\n" +
	"\n" +
	"GetAuction\x12 .proto.auction.GetAuctionRequest\x1a!.proto.auction.GetAuctionResponse\x12W\n" +
	"\fListAuctions\x12\".proto.auction.ListAuctionsRequest\x1a#.proto.auction.ListAuctionsResponse\x12Z\n" +
	"\rUpdateAuction\x12#.proto.auction.UpdateAuctionRequest\x1a$.proto.auction.UpdateAuctionResponse\x12W\n" +
	"\fCloseAuction\x12\".proto.auction.CloseAuctionRequest\x1a#.proto.auction.CloseAuctionResponseB8Z6github.com/temesgen-abebayehu/bidflow/backend/proto/pbb\x06proto3"

var (
	file_proto_auction_proto_rawDescOnce sync.Once
	file_proto_auction_proto_rawDescData []byte
)

func file_proto_auction_proto_rawDescGZIP() []byte {
	file_proto_auction_proto_rawDescOnce.Do(func() {
		file_proto_auction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auction_proto_rawDesc), len(file_proto_auction_proto_rawDesc)))
	})
	return file_proto_auction_proto_rawDescData
}

var file_proto_auction_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_auction_proto_goTypes = []any{
	(*Auction)(nil),               // 0: proto.auction.Auction
	(*CreateAuctionRequest)(nil),  // 1: proto.auction.CreateAuctionRequest
	(*CreateAuctionResponse)(nil), // 2: proto.auction.CreateAuctionResponse
	(*GetAuctionRequest)(nil),     // 3: proto.auction.GetAuctionRequest
	(*GetAuctionResponse)(nil),    // 4: proto.auction.GetAuctionResponse
	(*ListAuctionsRequest)(nil),   // 5: proto.auction.ListAuctionsRequest
	(*ListAuctionsResponse)(nil),  // 6: proto.auction.ListAuctionsResponse
	(*UpdateAuctionRequest)(nil),  // 7: proto.auction.UpdateAuctionRequest
	(*UpdateAuctionResponse)(nil), // 8: proto.auction.UpdateAuctionResponse
	(*CloseAuctionRequest)(nil),   // 9: proto.auction.CloseAuctionRequest
	(*CloseAuctionResponse)(nil),  // 10: proto.auction.CloseAuctionResponse
	(*BidRequest)(nil),            // 11: proto.auction.BidRequest
	(*BidResponse)(nil),           // 12: proto.auction.BidResponse
	(*StatusRequest)(nil),         // 13: proto.auction.StatusRequest
	(*StatusResponse)(nil),        // 14: proto.auction.StatusResponse
}
var file_proto_auction_proto_depIdxs = []int32{
	0,  // 0: proto.auction.CreateAuctionResponse.auction:type_name -> proto.auction.Auction
	0,  // 1: proto.auction.GetAuctionResponse.auction:type_name -> proto.auction.Auction
	0,  // 2: proto.auction.ListAuctionsResponse.auctions:type_name -> proto.auction.Auction
	0,  // 3: proto.auction.UpdateAuctionResponse.auction:type_name -> proto.auction.Auction
	11, // 4: proto.auction.AuctionService.ValidateBid:input_type -> proto.auction.BidRequest
	13, // 5: proto.auction.AuctionService.GetAuctionStatus:input_type -> proto.auction.StatusRequest
	1,  // 6: proto.auction.AuctionService.CreateAuction:input_type -> proto.auction.CreateAuctionRequest
	3,  // 7: proto.auction.AuctionService.GetAuction:input_type -> proto.auction.GetAuctionRequest
	5,  // 8: proto.auction.AuctionService.ListAuctions:input_type -> proto.auction.ListAuctionsRequest
	7,  // 9: proto.auction.AuctionService.UpdateAuction:input_type -> proto.auction.UpdateAuctionRequest
	9,  // 10: proto.auction.AuctionService.CloseAuction:input_type -> proto.auction.CloseAuctionRequest
	12, // 11: proto.auction.AuctionService.ValidateBid:output_type -> proto.auction.BidResponse
	14, // 12: proto.auction.AuctionService.GetAuctionStatus:output_type -> proto.auction.StatusResponse
	2,  // 13: proto.auction.AuctionService.CreateAuction:output_type -> proto.auction.CreateAuctionResponse
	4,  // 14: proto.auction.AuctionService.GetAuction:output_type -> proto.auction.GetAuctionResponse
	6,  // 15: proto.auction.AuctionService.ListAuctions:output_type -> proto.auction.ListAuctionsResponse
	8,  // 16: proto.auction.AuctionService.UpdateAuction:output_type -> proto.auction.UpdateAuctionResponse
	10, // 17: proto.auction.AuctionService.CloseAuction:output_type -> proto.auction.CloseAuctionResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_auction_proto_init() }
func file_proto_auction_proto_init() {
	if File_proto_auction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auction_proto_rawDesc), len(file_proto_auction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auction_proto_goTypes,
		DependencyIndexes: file_proto_auction_proto_depIdxs,
		MessageInfos:      file_proto_auction_proto_msgTypes,
	}.Build()
	File_proto_auction_proto = out.File
	file_proto_auction_proto_goTypes = nil
	file_proto_auction_proto_depIdxs = nil
}
