// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: bidding.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaceBidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     string                 `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	BidderId      string                 `protobuf:"bytes,2,opt,name=bidder_id,json=bidderId,proto3" json:"bidder_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBidRequest) Reset() {
	*x = PlaceBidRequest{}
	mi := &file_bidding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBidRequest) ProtoMessage() {}

func (x *PlaceBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bidding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBidRequest.ProtoReflect.Descriptor instead.
func (*PlaceBidRequest) Descriptor() ([]byte, []int) {
	return file_bidding_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceBidRequest) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

func (x *PlaceBidRequest) GetBidderId() string {
	if x != nil {
		return x.BidderId
	}
	return ""
}

func (x *PlaceBidRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PlaceBidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           *Bid                   `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBidResponse) Reset() {
	*x = PlaceBidResponse{}
	mi := &file_bidding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBidResponse) ProtoMessage() {}

func (x *PlaceBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bidding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBidResponse.ProtoReflect.Descriptor instead.
func (*PlaceBidResponse) Descriptor() ([]byte, []int) {
	return file_bidding_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceBidResponse) GetBid() *Bid {
	if x != nil {
		return x.Bid
	}
	return nil
}

type GetBidsByAuctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     string                 `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBidsByAuctionRequest) Reset() {
	*x = GetBidsByAuctionRequest{}
	mi := &file_bidding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBidsByAuctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBidsByAuctionRequest) ProtoMessage() {}

func (x *GetBidsByAuctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bidding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBidsByAuctionRequest.ProtoReflect.Descriptor instead.
func (*GetBidsByAuctionRequest) Descriptor() ([]byte, []int) {
	return file_bidding_proto_rawDescGZIP(), []int{2}
}

func (x *GetBidsByAuctionRequest) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

type GetBidsByAuctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bids          []*Bid                 `protobuf:"bytes,1,rep,name=bids,proto3" json:"bids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBidsByAuctionResponse) Reset() {
	*x = GetBidsByAuctionResponse{}
	mi := &file_bidding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBidsByAuctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBidsByAuctionResponse) ProtoMessage() {}

func (x *GetBidsByAuctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bidding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBidsByAuctionResponse.ProtoReflect.Descriptor instead.
func (*GetBidsByAuctionResponse) Descriptor() ([]byte, []int) {
	return file_bidding_proto_rawDescGZIP(), []int{3}
}

func (x *GetBidsByAuctionResponse) GetBids() []*Bid {
	if x != nil {
		return x.Bids
	}
	return nil
}

type Bid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuctionId     string                 `protobuf:"bytes,2,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	BidderId      string                 `protobuf:"bytes,3,opt,name=bidder_id,json=bidderId,proto3" json:"bidder_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bid) Reset() {
	*x = Bid{}
	mi := &file_bidding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_bidding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_bidding_proto_rawDescGZIP(), []int{4}
}

func (x *Bid) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bid) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

func (x *Bid) GetBidderId() string {
	if x != nil {
		return x.BidderId
	}
	return ""
}

func (x *Bid) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Bid) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_bidding_proto protoreflect.FileDescriptor

const file_bidding_proto_rawDesc = "" +
	"\n" +
	"\rbidding.proto\x12\rproto.bidding\x1a\x1fgoogle/protobuf/timestamp.proto\"e\n" +
	"\x0fPlaceBidRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\tR\tauctionId\x12\x1b\n" +
	"\tbidder_id\x18\x02 \x01(\tR\bbidderId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"8\n" +
	"\x10PlaceBidResponse\x12$\n" +
	"\x03bid\x18\x01 \x01(\v2\x12.proto.bidding.BidR\x03bid\"8\n" +
	"\x17GetBidsByAuctionRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\tR\tauctionId\"B\n" +
	"\x18GetBidsByAuctionResponse\x12&\n" +
	"\x04bids\x18\x01 \x03(\v2\x12.proto.bidding.BidR\x04bids\"\xa3\x01\n" +
	"\x03Bid\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x02 \x01(\tR\tauctionId\x12\x1b\n" +
	"\tbidder_id\x18\x03 \x01(\tR\bbidderId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\xc2\x01\n" +
	"\x0eBiddingService\x12K\n" +
	"\bPlaceBid\x12\x1e.proto.bidding.PlaceBidRequest\x1a\x1f.proto.bidding.PlaceBidResponse\x12c\n" +
	"\x10GetBidsByAuction\x12&.proto.bidding.GetBidsByAuctionRequest\x1a'.proto.bidding.GetBidsByAuctionResponseB8Z6github.com/temesgen-abebayehu/bidflow/backend/proto/pbb\x06proto3"

var (
	file_bidding_proto_rawDescOnce sync.Once
	file_bidding_proto_rawDescData []byte
)

func file_bidding_proto_rawDescGZIP() []byte {
	file_bidding_proto_rawDescOnce.Do(func() {
		file_bidding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bidding_proto_rawDesc), len(file_bidding_proto_rawDesc)))
	})
	return file_bidding_proto_rawDescData
}

var file_bidding_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_bidding_proto_goTypes = []any{
	(*PlaceBidRequest)(nil),          // 0: proto.bidding.PlaceBidRequest
	(*PlaceBidResponse)(nil),         // 1: proto.bidding.PlaceBidResponse
	(*GetBidsByAuctionRequest)(nil),  // 2: proto.bidding.GetBidsByAuctionRequest
	(*GetBidsByAuctionResponse)(nil), // 3: proto.bidding.GetBidsByAuctionResponse
	(*Bid)(nil),                      // 4: proto.bidding.Bid
	(*timestamppb.Timestamp)(nil),    // 5: google.protobuf.Timestamp
}
var file_bidding_proto_depIdxs = []int32{
	4, // 0: proto.bidding.PlaceBidResponse.bid:type_name -> proto.bidding.Bid
	4, // 1: proto.bidding.GetBidsByAuctionResponse.bids:type_name -> proto.bidding.Bid
	5, // 2: proto.bidding.Bid.timestamp:type_name -> google.protobuf.Timestamp
	0, // 3: proto.bidding.BiddingService.PlaceBid:input_type -> proto.bidding.PlaceBidRequest
	2, // 4: proto.bidding.BiddingService.GetBidsByAuction:input_type -> proto.bidding.GetBidsByAuctionRequest
	1, // 5: proto.bidding.BiddingService.PlaceBid:output_type -> proto.bidding.PlaceBidResponse
	3, // 6: proto.bidding.BiddingService.GetBidsByAuction:output_type -> proto.bidding.GetBidsByAuctionResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bidding_proto_init() }
func file_bidding_proto_init() {
	if File_bidding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bidding_proto_rawDesc), len(file_bidding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bidding_proto_goTypes,
		DependencyIndexes: file_bidding_proto_depIdxs,
		MessageInfos:      file_bidding_proto_msgTypes,
	}.Build()
	File_bidding_proto = out.File
	file_bidding_proto_goTypes = nil
	file_bidding_proto_depIdxs = nil
}
